routes/web.php
<?php

Route::group(['middleware' => 'verifique'], function(){
Route::get('home', 'HomeController@index')->middleware('verifique');
});

Route::get('/', function () {
    return view('bem-vindo');
});


Route::get('/verifique/email',function(){
     return view('mails.verificacao-email');
})->name('verifique-email')->middleware('auth');


Route::get('/users/confirmation/{token}','Auth\RegisterController@confirmation')->name('confirmation');

Route::get('/mail','MailController@index');



Route::get('/responsavel', function () {
    return view('responsavel.index');
});

Route::resource('disciplinas', 'DisciplinaController');
Route::resource('turma', 'TurmaController');
Route::resource('alunoturma', 'AlunoTurmaController');
Route::resource('nota', 'NotaController');
Route::resource('professor', 'ProfessorController');
Route::resource('aluno', 'AlunoController');
Route::resource('funcionario', 'FuncionarioController');
Route::resource('horario', 'HorarioController');
Route::resource('serie', 'SerieController');
Route::resource('bimestre', 'BimestreController');
Route::resource('tiponotas', 'TipoNotaController');

Route::get('horario/turma/{turma}/professor/{professor}/disciplina/{disciplina}/', 'HorarioController@getHorario');
Route::get('getprofessores/{id_turma}/{id_disciplina}','ProfessorController@getProfessors');

Route::group(['prefix'=>'alunos'], function(){
  //Route::get('alunos/semturma','AlunoController@getAlunosNaoVinculados'); modificada
  Route::get('vinculo=false','AlunoController@getAlunosNaoVinculados');
  Route::get('vinculo=true','AlunoController@getAlunosVinculados');
});


Route::get('turmas','TurmaController@getTurmas');

Route::group(['prefix'=>'turma'], function(){
  Route::get('{id}/alunos','AlunoTurmaController@getAlunosTurma');
});

Route::group(['prefix'=>'disciplinas'], function(){
  //Route::get('/getdisciplinasNotIn','DisciplinaController@getDisciplinasHorario');  modificada
  Route::get('professor/{idProfessor}/turma/{idTurma}','DisciplinaController@getDisciplinasHorario');

  //Route::get('/getdisciplinas/{id_turma}','DisciplinaController@getDisciplinas'); modificada
  Route::get('turma/{idTurma}','DisciplinaController@getDisciplinas');
});

Route::group(['prefix'=>'dashboard'], function(){
  Route::get('administrador',function(){
    return view('dashboards.administrador.dashboard');
  });
  Route::get('professor',function(){
    return view('dashboards.professor.dashboard');
  });

  Route::get('aluno',function(){
    return view('dashboards.administrador.aluno');
  });

  Route::get('aluno/create',function(){
    return view('dashboards.aluno.create');
  });

});

Route::get('getalunos', 'AlunoController@getAlunos');

Auth::routes();

app/Models/Disciplina.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Disciplina extends Model {

    protected $fillable = ['descricao','tipo'];

    public $rules = [
      'descricao' => 'required',
      'tipo'  => 'required'
    ];

    public $timetamps = false;

}

app/Http/Controllers/DisciplinaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\DisciplinaRequest;
use App\Models\Disciplina;
use App\Models\Horario;
use Gate;

class DisciplinaController extends Controller
{

    private $disciplina;

    function __construct(Disciplina $disciplina)
    {
        $this->disciplina = $disciplina;
    }

    public function listar()
    {
        $disciplinas = $this->disciplina->all();
        $response = [
            'tipos' => [
                'Reprova' => 'Reprova',
                'Não Reprova' => 'Não Reprova'
            ],
            'data' => $disciplinas
        ];
        return response()->json($response);
    }

    public function index()
    {
        $tipos = ['Reprova' => 'Reprova', 'Não Reprova' => 'Não Reprova'];
        $disciplinas = $this->disciplina->paginate(10);

        return view('disciplina.index', compact('disciplinas', 'tipos'));
    }

    public function create()
    {
        $title = 'Pagina Cadastro';
        $tipos = ['Reprova' => 'Reprova', 'Não Reprova' => 'Não Reprova'];
        return view('disciplina.index', compact('tipos', 'title'));
    }

    public function store(DisciplinaRequest $request)
    {
        $dados = $request->all();
        $insert = $this->disciplina->create($dados);

        if ($insert) {
            return redirect()->route('disciplinas.index');
        } else {
            return redirect()->route('disciplinas.store');
        }
    }

    public function show($id)
    {
        $dis = $this->disciplina->find($id);
        $delete = $dis->delete();
        if ($delete) {
            return redirect()->route('disciplinas.index');
        }
    }

    public function edit($id)
    {
        $tipos = ['Reprova' => 'Reprova', 'Não Reprova' => 'Não Reprova'];
        $disciplina = $this->disciplina->find($id);
        $title = "Editar: {{$disciplina->descricao}}";
        return view('disciplina.create', compact('disciplina', 'title', 'tipos'));
    }

    public function update(DisciplinaRequest $request, $id)
    {
        $dados = request()->except('_token', '_method');
        $disc = $this->disciplina->find($id);
        if ($disc->update($dados)) {
            return redirect()->route('disciplinas.index');
        } else {
            return redirect('disciplinas.edit');
        }
    }


/**
  Retorna as disciplinas que o professor não lecina em determinada turma!
Rota: disciplinas/professor/{idProfessor}/turma/{idTurma}/
*/
    public static function getDisciplinasHorario($idProfessor,$idTurma)
    {
        $ids_disciplinas = Horario::select('id_disciplina')->where('id_professor', '=', $idProfessor)->where('id_turma', '=',$idTurma)->get();
        return Disciplina::whereNotIn('id', $ids_disciplinas)->get();
    }

/**
  Retorna as discipinas de uma determinada turma!
  Rota: /disciplinas/turma/{id_turma}
*/
    public static function getDisciplinas($idTurma)
    {
        $ids_disciplinas = Horario::select('id_disciplina')->where('id_turma', '=', $idTurma)->get();
        return Disciplina::whereIn('id', $ids_disciplinas)->get();
    }

}

resources/views/disciplina/create.blade.php
@extends('templates.template')
@section('content')
<div class="container">
    <div class="row">
        @if(isset($disciplina))
        {!! Form::model($disciplina,['route'=>['disciplinas.update', $disciplina->id],'class'=>'form','method'=>'put'])!!}
        @else
        {!!Form::open(['route'=>'disciplinas.store'])!!}
        @endif
        <div class="col s6 l6 m6">
            <label>Disciplina</label>
            {!! Form::text('descricao',null,['class'=>'validate','placeholder'=>'Nome da Disciplina'])!!}

            <label>Tipo</label>
            {!! Form::select('tipo', $tipos,null,['class'=>'input-field','required'=>""])!!}

            {!!Form::submit('Enviar',['class'=>'btn btn-primary'])!!}
              {!!Form::close()!!}
        </div>
    </div>

</div>
@endsection
@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
@endsection

resources/views/disciplina/index.blade.php
@extends('templates.template')

@section('content')

<div class="alert">
@if(isset($errors) && count($errors)>0)
  @foreach ($errors->all() as $error)
{{$error}}
  @endforeach
@endif

</div>
<div class="container">
  <div class="card">
      <table class="highlight centered bordered">
        <thead>
            <tr>
                <th>Disciplina</th>
                <th>Tipo</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                @if(isset($disciplinas))
                @foreach($disciplinas as $disciplin)
                <td> {{$disciplin->descricao}}</td>
                <td> {{$disciplin->tipo}}</td>
                <td>
                    <a class="mdi mdi-account-edit mdi-24px" href="{{route('disciplinas.edit',$disciplin->id)}}"></a>
                    <a class="mdi mdi-delete mdi-24px" href="{{route('disciplinas.show',$disciplin->id)}}"></a></td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>
  </div>


<div class="paginate center">
{!!  $disciplinas->links('vendor.pagination.materiallize')!!}
</div>

    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light red" data-target="modal1" href="{{route('disciplinas.create')}}"><i class="mdi mdi-plus"></i></a>
    </div>
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Disciplina</h4>
            <div class="row">
                @if(isset($disciplina))
                {!! Form::model($disciplina,['route'=>['disciplinas.update', $disciplina->id],'class'=>'form','method'=>'put'])!!}
                @else
                @endif
                {!!Form::open(['route'=>'disciplinas.store'])!!}

                <div class="col s12 l12 m12">
                    <label>Disciplina</label>
                    {!! Form::text('descricao',null,['class'=>'validate','placeholder'=>'Nome da Disciplina'])!!}

                    <label>Tipo</label>
                    {!! Form::select('tipo', $tipos,null,['class'=>'input-field','required'=>""])!!}

                    {!!Form::submit('Enviar',['class'=>'btn btn-primary'])!!}
                    {!!Form::close()!!}
                </div>
            </div>
        </div>
    </div>

   </div>


    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect waves-light darken-3 waves-purple" data-target="modal1" href="{{route('disciplinas.create')}}"><i class="mdi mdi-plus"></i></a>
    </div>
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Disciplina</h4>
            <div class="row">
                @if(isset($disciplina))
                {!! Form::model($disciplina,['route'=>['disciplinas.update', $disciplina->id],'class'=>'form','method'=>'put'])!!}
                @else
                @endif
                {!!Form::open(['route'=>'disciplinas.store'])!!}

                <div class="col s12 l12 m12">
                    <label>Disciplina</label>
                    {!! Form::text('descricao',null,['class'=>'validate','placeholder'=>'Nome da Disciplina'])!!}

                    <label>Tipo</label>
                    {!! Form::select('tipo', $tipos,null,['class'=>'input-field','required'=>""])!!}

                    {!!Form::submit('Enviar',['class'=>'btn btn-primary'])!!}
                    {!!Form::close()!!}
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
@endsection