routes/web.php
<?php

Route::group(['middleware' => 'verifique'], function(){
Route::get('home', 'HomeController@index')->middleware('verifique');
});

Route::get('/', function () {
    return view('bem-vindo');
});


Route::get('/verifique/email',function(){
     return view('mails.verificacao-email');
})->name('verifique-email')->middleware('auth');


Route::get('/users/confirmation/{token}','Auth\RegisterController@confirmation')->name('confirmation');

Route::get('/mail','MailController@index');



Route::get('/responsavel', function () {
    return view('responsavel.index');
});

Route::resource('disciplinas', 'DisciplinaController');
Route::resource('turma', 'TurmaController');
Route::resource('alunoturma', 'AlunoTurmaController');
Route::resource('nota', 'NotaController');
Route::resource('professor', 'ProfessorController');
Route::resource('aluno', 'AlunoController');
Route::resource('funcionario', 'FuncionarioController');
Route::resource('horario', 'HorarioController');
Route::resource('serie', 'SerieController');
Route::resource('bimestre', 'BimestreController');
Route::resource('tiponotas', 'TipoNotaController');

Route::get('horario/turma/{turma}/professor/{professor}/disciplina/{disciplina}/', 'HorarioController@getHorario');
Route::get('getprofessores/{id_turma}/{id_disciplina}','ProfessorController@getProfessors');

Route::group(['prefix'=>'alunos'], function(){
  //Route::get('alunos/semturma','AlunoController@getAlunosNaoVinculados'); modificada
  Route::get('vinculo=false','AlunoController@getAlunosNaoVinculados');
  Route::get('vinculo=true','AlunoController@getAlunosVinculados');
});


Route::get('turmas','TurmaController@getTurmas');

Route::group(['prefix'=>'turma'], function(){
  Route::get('{id}/alunos','AlunoTurmaController@getAlunosTurma');
});

Route::group(['prefix'=>'disciplinas'], function(){
  //Route::get('/getdisciplinasNotIn','DisciplinaController@getDisciplinasHorario');  modificada
  Route::get('professor/{idProfessor}/turma/{idTurma}','DisciplinaController@getDisciplinasHorario');

  //Route::get('/getdisciplinas/{id_turma}','DisciplinaController@getDisciplinas'); modificada
  Route::get('turma/{idTurma}','DisciplinaController@getDisciplinas');
});

Route::group(['prefix'=>'dashboard'], function(){
  Route::get('administrador',function(){
    return view('dashboards.administrador.dashboard');
  });
  Route::get('professor',function(){
    return view('dashboards.professor.dashboard');
  });

  Route::get('aluno',function(){
    return view('dashboards.administrador.aluno');
  });

  Route::get('aluno/create',function(){
    return view('dashboards.aluno.create');
  });

});

Route::get('getalunos', 'AlunoController@getAlunos');

Auth::routes();

app/Models/Turma.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

use App\Models\Horario;

class Turma extends Model
{

    protected $fillable = ['descricao', 'turno','ano','id_serie'];

 public function serie(): BelongsTo {
return $this->belongsTo(Serie::class,'id_serie');
 }

 public function alunos() {
 return $this->belongsToMany('App\Models\Aluno', 'aluno_turma', 'id_turma', 'matricula_aluno')->withPivot(['numero_chamada']);
 }

 public function horarios(): HasMany {
        return $this->hasMany(Horario::class,'id');
    }
}

app/Http/Controllers/TurmaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\TurmaRequest;
use App\Models\Turma;
use App\Models\Serie;

class TurmaController extends Controller
{

    private $turma;

    function __construct(Turma $turma)
    {
        $this->turma = $turma;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "Index Turma";
        $turnos = ['Manhã' => 'Manhã', 'Tarde' => 'Tarde', 'Noite' => 'Noite'];
        $turmas = $this->turma->all();
        return view('turma.index', compact('title', 'turmas','turnos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Serie $serie)
    {
         $series = $serie->all(['id', 'descricao'])->pluck('descricao','id');
        $title = "Cadastro Turma";
        $turnos = ['Manhã' => 'Manhã', 'Tarde' => 'Tarde', 'Noite' => 'Noite'];
        return view('turma.create', compact('title', 'turnos','series'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(TurmaRequest $request)
    {
      $dados = $request->all();
      $insert = $this->turma->create($dados);

        if ($insert) {
            return redirect()->route('turma.index');
        } else {
            return redirect()->route('turma.store');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dis = $this->turma->find($id);
        $delete = $dis->delete();
        if ($delete) {
            return redirect()->route('turma.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $series = Serie::all(['id', 'descricao'])->pluck('descricao','id');
        $turma = $this->turma->find($id);
        $title = "Editar: {{$turma->descricao}}";
        $turnos = ['Manhã' => 'Manhã', 'Tarde' => 'Tarde', 'Noite' => 'Noite'];
        return view('turma.create', compact('turma', 'title', 'turnos','series'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(TurmaRequest $request, $id)
    {
        $dados = request()->all();
        $tur = $this->turma->find($id);
        if ($tur->update($dados)) {
            return redirect()->route('turma.index');
        } else {
            return redirect('turma.edit');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
    Retorna um Json com todas as turmas existentes!
    */
    public function getTurmas()
    {
      $turmas = $this->turma->all();
      return response()->json($turmas);
    }

}

resources/views/turma/create.blade.php
@extends('templates.template')
@section('content')
@if(isset($errors) && count($errors)>0)
<div class="alert">
  @foreach($errors->all() as $error)
  {{$error}}<br>
  @endforeach

</div>
  @endif
    <div class="container">

        <div class="container">
            <p>
            <div class="card-header center teal darken-3">
                <i class="mdi mdi-alphabetical mdi-48px white-text"></i>
            </div>

            <div class="card-panel center">
            @if(isset($turma))
                {!! Form::model($turma,['route'=>['turma.update', $turma->id],'class'=>'form','method'=>'put'])!!}
            @else
                {!!Form::open(['route'=>'turma.store'])!!}
            @endif
            <div class="row">
                <div class="input-field col s12 m6 l6">
                    {!! Form::text('descricao',null,['class'=>'validate','data-length'=>'10'])!!}
                    <label for="descricao">Turma</label>
                </div>
                <div class="input-field col s12 m6 l6">
                    {!! Form::text('ano',null,['class'=>'datepicker'])!!}
                    <label for="ano">Ano</label>
                </div>
            </div>

            <div class="row">
                <div class="input-field col s12 m6 l6">
                    {!! Form::select('turno',$turnos,null,['required'=>""])!!}
                    <label for="turno">Turno</label>
                </div>

                <div class="input-field col s12 m6 l6">
                    {!! Form::select('id_serie', $series,null,['class'=>'validate','required'=>""])!!}
                    <label for="id_serie">Series</label>
                </div>
            </div>

            {!!Form::submit('Enviar',['class'=>'btn btn-primary'])!!}
            {!!Form::close()!!}


    </div>

@endsection

@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
@endsection

resources/views/turma/index.blade.php
@extends('templates.template')

@section('content')
    @if(isset($turmas))
        <table class="highlight centered">
            <thead>
            <tr>
                <th>Descrição</th>
                <th>Turno</th>
                <th>Ano</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>
            @foreach($turmas as $turma)
                <tr>
                    <td>{{$turma->descricao}}</td>
                    <td>{{$turma->turno}}</td>
                    <td>{{$turma->ano}}</td>

                    <td>
                      <a class="mdi mdi-sync mdi-24px" href="alunoturma"></a>
                      <a class="mdi mdi-account-edit mdi-24px" href="{{route('turma.edit',$turma->id)}}"></a>
                      <a class="mdi mdi-delete mdi-24px" href="{{route('turma.show',$turma->id)}}"></a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @endif
    <div class="fixed-action-btn">
        <a class="btn-floating btn-large waves-effect green waves-purple" data-target="modal1"
           href="{{route('turma.create')}}"><i class="mdi mdi-plus"></i> </a>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
@endsection

resources/views/turma/vincular.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">

<script>
     window.Laravel = <?php echo json_encode([
         'csrfToken' => csrf_token(),
     ]); ?>
</script>
      <title>Sincronizar Alunos</title>
</head>
<body>
  <div id="app">

    <md-toolbar>
  <h1 class="md-title">Sincronizar Alunos</h1>

    </md-toolbar>
    <aluno-turma></aluno-turma>
  </div>


</body>

<script src="js/app.js"></script>

</html>