routes/web.php
<?php

Route::group(['middleware' => 'verifique'], function(){
Route::get('home', 'HomeController@index')->middleware('verifique');
});

Route::get('/', function () {
    return view('bem-vindo');
});


Route::get('/verifique/email',function(){
     return view('mails.verificacao-email');
})->name('verifique-email')->middleware('auth');


Route::get('/users/confirmation/{token}','Auth\RegisterController@confirmation')->name('confirmation');

Route::get('/mail','MailController@index');



Route::get('/responsavel', function () {
    return view('responsavel.index');
});

Route::resource('disciplinas', 'DisciplinaController');
Route::resource('turma', 'TurmaController');
Route::resource('alunoturma', 'AlunoTurmaController');
Route::resource('nota', 'NotaController');
Route::resource('professor', 'ProfessorController');
Route::resource('aluno', 'AlunoController');
Route::resource('funcionario', 'FuncionarioController');
Route::resource('horario', 'HorarioController');
Route::resource('serie', 'SerieController');
Route::resource('bimestre', 'BimestreController');
Route::resource('tiponotas', 'TipoNotaController');

Route::get('horario/turma/{turma}/professor/{professor}/disciplina/{disciplina}/', 'HorarioController@getHorario');
Route::get('getprofessores/{id_turma}/{id_disciplina}','ProfessorController@getProfessors');

Route::group(['prefix'=>'alunos'], function(){
  //Route::get('alunos/semturma','AlunoController@getAlunosNaoVinculados'); modificada
  Route::get('vinculo=false','AlunoController@getAlunosNaoVinculados');
  Route::get('vinculo=true','AlunoController@getAlunosVinculados');
});


Route::get('turmas','TurmaController@getTurmas');

Route::group(['prefix'=>'turma'], function(){
  Route::get('{id}/alunos','AlunoTurmaController@getAlunosTurma');
});

Route::group(['prefix'=>'disciplinas'], function(){
  //Route::get('/getdisciplinasNotIn','DisciplinaController@getDisciplinasHorario');  modificada
  Route::get('professor/{idProfessor}/turma/{idTurma}','DisciplinaController@getDisciplinasHorario');

  //Route::get('/getdisciplinas/{id_turma}','DisciplinaController@getDisciplinas'); modificada
  Route::get('turma/{idTurma}','DisciplinaController@getDisciplinas');
});

Route::group(['prefix'=>'dashboard'], function(){
  Route::get('administrador',function(){
    return view('dashboards.administrador.dashboard');
  });
  Route::get('professor',function(){
    return view('dashboards.professor.dashboard');
  });

  Route::get('aluno',function(){
    return view('dashboards.administrador.aluno');
  });

  Route::get('aluno/create',function(){
    return view('dashboards.aluno.create');
  });

});

Route::get('getalunos', 'AlunoController@getAlunos');

Auth::routes();

app/Models/Professor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Professor extends Model
{
    protected $table = 'professors';
    protected $fillable = ['nome', 'cpf', 'bairro', 'naturalidade', 'nascionalidade', 'sexo', 'email', 'ctps', 'data_emissao', 'profissao', 'data_nascimento', 'estado_civil', 'numero_residencia', 'orgao_emissor', 'pis_pasep', 'pos_graduacao', 'cidade', 'etinia', 'grau_instrucao', 'rg', 'celular', 'endereco', 'secao',
    'serie', 'situacao', 'titulo_eleitor', 'estado', 'complemento', 'cep'];

    public $rules = ['name' => 'required|max:255'];

    public function horarios(): HasMany
    {
        return $this->hasMany(Horario::class, 'id_professor');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/ProfessorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfessorResquest;
use App\Models\Professor;
use App\Models\Horario;
use App\User;
class ProfessorController extends Controller
{

    private $professor;

    function __construct(Professor $professor)
    {
          $this->middleware('auth');
        $this->professor = $professor;
    }

    public function index()
    {
        $professores = $this->professor->all();
        return view('professor.index', compact('professores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = 'Cadastro Professor';
        return view('professor.create', compact('title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProfessorResquest $request)
    {
      $usuario = new User();
      $usuario->name= $request->nome;
      $usuario->email = $request->email;
      $usuario->password = bcrypt('123456789');
      $usuario->confirmed = false;
      $usuario->save();

        if($usuario){
          $dados = $request->all();
          $professor = $this->professor->create($dados);
          $insert = $professor->user()->associate($usuario);
          $insert->save();
  
          if ($insert) {
              return redirect()->route('professor.index');
          } else {
              return redirect()->route('professor.store');
          }

        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $prof = $this->professor->find($id);
        $delete = $prof->delete();
        if ($delete) {
            return redirect()->route('professor.index');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $professor = $this->professor->find($id);
        return view('professor.create', compact('professor'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProfessorResquest $request, $id)
    {
        $dados = request()->except('_token', '_method');
        $prof = $this->professor->find($id);
        if ($prof->update($dados)) {
            return redirect()->route('professor.index');
        } else {
            return redirect('professor.edit');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function retornarTurmas()
    {
        $this->professor('horarios')->join('turmas', function ($join) {
            $join->on('horarios.id_professor', '=', 'professor.id');
        })
            ->get();
    }

    public static function getProfessors($id_Tur, $id_d)
    {
        $ids_professores = Horario::select('id_professor')->where('id_turma', '=', $id_Tur)->where('id_disciplina', '=', $id_d)->get();
        return Professor::whereIn('id', $ids_professores)->get();
    }


}

resources/views/professor/create.blade.php
@extends('templates.template')
@if(isset($errors) && count($errors)>0)
    @foreach($errors->all() as $error)
  {{$error}}<br>
    @endforeach
@endif

@section('content')
    @if(isset($professor))
        {!! Form::model($professor,['route'=>['professor.update', $professor->id],'class'=>'form','method'=>'put'])!!}
    @else
        {!!Form::open(['route' =>'professor.store','novalidate'=>'novalidate','id'=>'form'])!!}
    @endif
    <div class="container" onload="Materialize.fadeInImage('#image-test')">
        <div class="card-panel">
            <div class="card-title">

            <span class="green-text text-darken-3"><h3>Cadastro Professor</h3>
        <p>Informe os dados</p></span>
            </div>
            <p>
            <div class="card-content">
                <div class="row">
                    <div class="input-field inline col s12 m6 l6">
                        <label for="nome">Nome Professor</label>
                        {!! Form::text('nome',null,['class'=>'validate input-field', 'aria-describedby'=>'basic-addon1','id'=>'nome','minlength'=>'10','required'])!!}
                        @if($errors->has('nome'))
                        <span class="red-text">{{$errors->first('nome')}}</span>
                        @endif

                    </div>

                    <div class="input-field col s6 m3 l3">
                        {!! Form::select('sexo', ['M' => 'Masculino', 'F' => 'Feminino'],null,['class'=>'validate ','id'=>'sexo'])!!}
                        <label for="sexo">Sexo</label>
                    </div>

                    <div class="input-field col s6 m3 l3">
                        {!!Form::text('data_nascimento',null,['class'=>'datepicker','id'=>'data_nascimento'])!!}
                        <label for="data_nascimento">Data Nascimento</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('cpf',null,['class'=>'validate','id'=>'cpf','onkeypress'=>'mascara(this,cpf)'])!!}
                        <label for="cpf">CPF</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('naturalidade',null,['class'=>'validate','id'=>'naturalidade'])!!}
                        <label for="naturalidade">Naturalidade</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('nascionalidade',null,['class'=>'validate','id'=>'nascionalidade'])!!}
                        <label for="nascionalidade">Nascionalidade</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('pis_pasep',null,['class'=>'validate','id'=>'pis_pasep'])!!}
                        <label for="pis_pasep">Pis/Pasep</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('grau_instrucao',null,['class'=>'validate','id'=>'grau_instrucao'])!!}
                        <label for="grau_instrucao">Grau</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('profissao',null,['class'=>'validate','id'=>'profissao'])!!}
                        <label for="profissao">Profissão</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('pos_graduacao',null,['class'=>'validate','id'=>'pos_graduacao'])!!}
                        <label for="pos_graduacao">Pos Graduacao</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('rg',null,['class'=>'validate','id'=>'rg'])!!}
                        <label for="rg">Identidade</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!! Form::select('orgao_emissor',[''=>'Selecione um Orgão','SSP'=>'SSP - Secretaria de Segurança Pública',
        'COREN'=>'COREN - Conselho Regional de Enfermagem',
        'CRA'=>'CRA - Conselho Regional de Administração',
        'CRAS'=>'CRAS - Conselho Regional de Assistentes Sociais',
        'CRB'=>'CRB - Conselho Regional de Biblioteconomia',
        'CRC'=>'CRC - Conselho Regional de Contabilidade',
        'CRE'=>'CRE - Conselho Regional de Estatística',
        'CREA'=>'CREA - Conselho Regional de Engenharia Arquitetura e Agronomia',
        'CRECI'=>'CRECI - Conselho Regional de Corretores de Imóveis',
        'CREFIT'=>'CREFIT - Conselho Regional de Fisioterapia e Terapia Ocupacional',
        'CRF'=>'CRF - Conselho Regional de Farmácia',
        'CRM'=>'CRM - Conselho Regional de Medicina',
        'CRN'=>'CRN - Conselho Regional de Nutrição',
        'CRO'=>'CRO - Conselho Regional de Odontologia',
        'CRP'=>'CRP - Conselho Regional de Psicologia',
        'CRPRE'=>'CRPRE - Conselho Regional de Profissionais de Relações Públicas',
        'CRQ'=>'CRQ - Conselho Regional de Química',
        'CRRC'=>'CRRC - Conselho Regional de Representantes Comerciais',
        'CRMV'=>'CRMV - Conselho Regional de Medicina Veterinária',
        'DPF'=>'DPF - Polícia Federal',
        'EST'=>'EST - Documentos Estrangeiros',
        'I CLA'=>'I CLA - Carteira de Identidade Classista',
        'MAE'=>'MAE - Ministério da Aeronáutica',
        'MEX'=>'MEX - Ministério do Exército',
        'MMA'=>'MMA - Ministério da Marinha',
        'OAB'=>'OAB - Ordem dos Advogados do Brasil',
        'OMB'=>'OMB - Ordens dos Músicos do Brasil',
        'IFP'=>'IFP - Instituto de Identificação Félix Pacheco',
        'OUT'=>'OUT - Outros Emissores'],null,['class'=>'validate','id'=>'orgao_emissor']) !!}
                        <label for="orgao_emissor">Emissor</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('data_emissao',null,['class'=>'datepicker','id'=>'data_emissao'])!!}
                        <label for="data_emissao">Data Emissão</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('etinia',null,['class'=>'validate','id'=>'etinia'])!!}
                        <label for="etinia">Etinia</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('ctps',null,['class'=>'validate','id'=>'ctps'])!!}
                        <label for="ctps">CTPS</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('email',null,['class'=>'validate','id'=>'email'])!!}
                        <label for="email">Email</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('celular',null,['class'=>'validate','id'=>'celular'])!!}
                        <label for="celular">Celular</label>
                    </div>

                    <div class="input-field col s12 m3 l3">
                        {!!Form::text('cep',null,['class'=>'validate','id'=>'cep'])!!}
                        <label for="cep">CEP</label>
                    </div>


                    <div class="input-field col s6 m2 l2">
                        {!!Form::select('estado_civil',['solteira'=>'Solteira','casada'=>'Casada','separada'=>'Separada'],null,['class'=>'validate','id'=>'estado_civil'])!!}
                        <label for="estado_civil">Estado civil</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('endereco',null,['class'=>'validate','id'=>'endereco'])!!}
                        <label for="endereco">Endereço</label>
                    </div>

                    <div class="input-field col s12 m2 l2">
                        {!!Form::text('numero_residencia',null,['class'=>'validate','id'=>'numero_residencia'])!!}
                        <label for="numero_residencia">Número</label>
                    </div>

                    <div class="input-field col s12 m4 l4">
                        {!!Form::select('estado',['AC'=>'Acre','AL'=>'Alagoas','AP'=>'Amapá','AM'=>'Amazonas','BA'=>'Bahia','CE'=>'Ceará','DF'=>'Distrito Federal','ES'=>'Espirito Santo','GO'=>'Goiás','MA'=>'Maranhão','MS'=>'Mato Grossodo Sul','MT'=>'Mato Grosso','MG'=>'Minas Gerais','PA'=>'Pará','PB'=>'Paraíba','PR'=>'Paraná','PE'=>'Pernambuco','PI'=>'Piauí','RJ'=>'Riode Janeiro','RN'=>'Rio Grande do Norte','RS'=>'Rio Grande do Sul','RO'=>'Rondônia','RR'=>'Roraima','SC'=>'Santa Catarina','SP'=>'São Paulo','SE'=>'Sergipe','TO'=>'Tocantins'],null,['class'=>'validate','id'=>'estado'])!!}
                        <label for="estado">Estado</label>

                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('complemento',null,['class'=>'validate','id'=>'complemento'])!!}
                        <label for="complemento">Complemento</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('bairro',null,['class'=>'validate','id'=>'bairro'])!!}
                        <label for="bairro">Bairro</label>
                    </div>

                    <div class="input-field col s12 m6 l6">
                        {!!Form::text('cidade',null,['class'=>'validate','id'=>'cidade'])!!}
                        <label for="cidade">Cidade</label>
                    </div>

                    <button class="btn waves-effect waves-light direct right" type="submit" name="action">Enviar
                        <i class="mdi mdi-arrow-bottom-rightt"></i>
                    </button>
                    {!!Form::close()!!}
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils.js")}}" type="text/javascript"></script>

@endsection

resources/views/professor/horario.blade.php
@extends('templates.template')

@section('content')
<div class="container">
    <div class="row col s12 m12 l12">

        <ul class="collapsible col s12 m4 l4" data-collapsible="accordion">
            @foreach($professores as $professor)
            <li>

                <div class="collapsible-header"><span class="new badge">4</span><i
                        class="mdi mdi-account-circle"></i>
                    {{$professor->nome}}
                </div>

                <div class="collapsible-body"><p><b>Disciplinas</b></p>
                    @foreach($professor->horarios as $horario)
                    {{$horario->disciplina->descricao}}
                      ,  {{$horario->turma->descricao}}
                        <a href="{{route('horario.show',$horario->id)}}">deletar</a>
                        <br>
                    @endforeach
                    <a href="{{route('horario.edit',$professor->id)}}">adicionar disciplina</a>


                </div>
            </li>
            @endforeach
        </ul>
    </div>


</div>




<div class="fixed-action-btn">

    <a class="btn-floating btn-large waves-effect green waves-purple tooltipped" data-position="top" data-delay="50"
       data-tooltip="Cadastar" data-target="modal1"
       href="{{route('horario.create')}}"><i class="mdi mdi-plus"></i></a>
</div>
@endsection
@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
@endsection

resources/views/professor/index.blade.php
@extends('templates.template')

@section('content')
    <div class="container">
        <table class="highlight centered">
            <thead>
            <tr>
                <th>Nome</th>
                <th>sexo</th>
                <th>Ação</th>
            </tr>
            </thead>
            <tbody>

                <tr>
                    @foreach($professores as $professor)
                    <td>{{$professor->nome}}</td>
                    <td>{{$professor->sexo}}</td>
                        <td>
                            <a class="mdi mdi-account-edit mdi-24px" href="{{route('professor.edit',$professor->id)}}"></a>
                            <a class="mdi mdi-delete mdi-24px" href="{{route('professor.show',$professor->id)}}"></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="fixed-action-btn">
            <a class="btn-floating btn-large waves-effect waves-light darken-4 waves-purple" data-target="modal1" href="{{route('professor.create')}}"><i class="mdi mdi-plus"></i></a>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{{url("materialize/js/materialize.js")}}" type="text/javascript"></script>
    <script src="{{url("/js/utils-materialize.js")}}" type="text/javascript"></script>
@endsection