routes/web.php
<?php

Route::group(['middleware' => 'verifique'], function(){
Route::get('home', 'HomeController@index')->middleware('verifique');
});

Route::get('/', function () {
    return view('bem-vindo');
});


Route::get('/verifique/email',function(){
     return view('mails.verificacao-email');
})->name('verifique-email')->middleware('auth');


Route::get('/users/confirmation/{token}','Auth\RegisterController@confirmation')->name('confirmation');

Route::get('/mail','MailController@index');



Route::get('/responsavel', function () {
    return view('responsavel.index');
});

Route::resource('disciplinas', 'DisciplinaController');
Route::resource('turma', 'TurmaController');
Route::resource('alunoturma', 'AlunoTurmaController');
Route::resource('nota', 'NotaController');
Route::resource('professor', 'ProfessorController');
Route::resource('aluno', 'AlunoController');
Route::resource('funcionario', 'FuncionarioController');
Route::resource('horario', 'HorarioController');
Route::resource('serie', 'SerieController');
Route::resource('bimestre', 'BimestreController');
Route::resource('tiponotas', 'TipoNotaController');

Route::get('horario/turma/{turma}/professor/{professor}/disciplina/{disciplina}/', 'HorarioController@getHorario');
Route::get('getprofessores/{id_turma}/{id_disciplina}','ProfessorController@getProfessors');

Route::group(['prefix'=>'alunos'], function(){
  //Route::get('alunos/semturma','AlunoController@getAlunosNaoVinculados'); modificada
  Route::get('vinculo=false','AlunoController@getAlunosNaoVinculados');
  Route::get('vinculo=true','AlunoController@getAlunosVinculados');
});


Route::get('turmas','TurmaController@getTurmas');

Route::group(['prefix'=>'turma'], function(){
  Route::get('{id}/alunos','AlunoTurmaController@getAlunosTurma');
});

Route::group(['prefix'=>'disciplinas'], function(){
  //Route::get('/getdisciplinasNotIn','DisciplinaController@getDisciplinasHorario');  modificada
  Route::get('professor/{idProfessor}/turma/{idTurma}','DisciplinaController@getDisciplinasHorario');

  //Route::get('/getdisciplinas/{id_turma}','DisciplinaController@getDisciplinas'); modificada
  Route::get('turma/{idTurma}','DisciplinaController@getDisciplinas');
});

Route::group(['prefix'=>'dashboard'], function(){
  Route::get('administrador',function(){
    return view('dashboards.administrador.dashboard');
  });
  Route::get('professor',function(){
    return view('dashboards.professor.dashboard');
  });

  Route::get('aluno',function(){
    return view('dashboards.administrador.aluno');
  });

  Route::get('aluno/create',function(){
    return view('dashboards.aluno.create');
  });

});

Route::get('getalunos', 'AlunoController@getAlunos');

Auth::routes();

resources/views/templates/nav-bar-menu.blade.php
<!-- Dropdown Structure -->

<nav>
    <div class="nav-wrapper teal darken-3">
        <a href="/home" class="brand-logo">Início</a>
        <a href="#" data-activates="slide-out" class="button-collapse"><i class="mdi mdi-menu"></i></a>
        <ul class="right hide-on-med-and-down">
            <li><a class="mdi mdi-lead-pencil tooltipped" data-position="botton" data-delay="50"
                   data-tooltip="Disciplina" href="{{url(route("disciplinas.index"))}}"></a></li>
            <li><a class="mdi mdi-face-profile tooltipped" data-position="botton" data-delay="50"
                   data-tooltip="Professor" href="{{url(route("professor.index"))}}"></a></li>
            <li><a class="mdi mdi-note tooltipped" data-position="botton" data-delay="50"
                   data-tooltip="Notas" href="{{url(route("nota.index"))}}"></a></li>
            <li><a class="mdi mdi-face tooltipped" data-position="botton" data-delay="50"
                   data-tooltip="Aluno" href="{{url(route("aluno.index"))}}"></a></li>
            <li><a class="mdi mdi-alphabetical tooltipped" data-position="botton" data-delay="50"
                   data-tooltip="Turma" href="{{url(route("turma.index"))}}"></a></li>
            <li><a class="mdi mdi-calendar tooltipped" data-position="botton" data-delay="50"
                   data-tooltip="Horario" href="{{url(route("horario.index"))}}"></a></li>
            @if(!Auth::guest())
                <ul class="right hide-on-med-and-down">
                    <!-- Dropdown Trigger -->

                    <li>
                        <a class="dropdown-button" href="#!" data-activates="dropdown"
                           data-beloworigin="true">{{Auth::user()->name }}
                            <i class="mdi-navigation-arrow-drop-down right"></i>
                        </a>
                    </li>
                </ul>

                <ul id="dropdown" class="dropdown-content collection">
                    <li class="collection-item avatar">
                        <img src="{{url('icones/man.png')}}" class="circle ">
                        <span class="title">{{Auth::user()->name }}</span>
                        <p>First Line</p>

                        <a class="secondary-content" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="mdi mdi-exit-to-app"></i>Sair
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
            @endif
        </ul>

        <ul class="side-nav" id="slide-out">
            <div class="collection">
                @if(!Auth::guest())
                    <li class="collection-item avatar teal darken-3">
                        <img src="{{url('icones/man.png')}}" alt="" class="circle">
                        <p class="title"> {{Auth::user()->name}}</p>
                        <a class="secondary-content white-text" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="mdi mdi-exit-to-app white-text"></i>
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                @endif
                <li><a class="mdi mdi-lead-pencil tooltipped" data-position="botton" data-delay="50"
                       data-tooltip="Disciplina" href="{{url(route("disciplinas.index"))}}">Disciplina</a></li>
                <li><a class="mdi mdi-face-profile tooltipped" data-position="botton" data-delay="50"
                       data-tooltip="Professor" href="{{url(route("professor.index"))}}">Professor</a></li>
                <li><a class="mdi mdi-note tooltipped" data-position="botton" data-delay="50"
                       data-tooltip="Notas" href="{{url(route("nota.index"))}}">Notas</a></li>
                <li><a class="mdi mdi-face tooltipped" data-position="botton" data-delay="50"
                       data-tooltip="Aluno" href="{{url(route("aluno.index"))}}">Aluno</a></li>
                <li><a class="mdi mdi-alphabetical tooltipped" data-position="botton" data-delay="50"
                       data-tooltip="Turma" href="{{url(route("turma.index"))}}">Turma</a></li>
                <li><a class="mdi mdi-calendar tooltipped" data-position="botton" data-delay="50"
                       data-tooltip="Horario" href="{{url(route("horario.index"))}}">Horario</a></li>
            </div>
        </ul>
    </div>
</nav>


<style type="text/css">
    .brand-logo {
        font-weight: 900;
    }

    .dropdown-content {
        background-color: #FFFFFF;
        margin: 0;
        display: none;
        min-width: 300px; /* Changed this to accomodate content width */
        max-height: auto;
        margin-left: -1px; /* Add this to keep dropdown in line with edge of navbar */
        overflow: hidden; /* Changed this from overflow-y:auto; to overflow:hidden; */
        opacity: 0;
        position: absolute;
        white-space: nowrap;
        z-index: 1;
        will-change: width, height;
    }
</style>

resources/views/templates/template.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <title>Controle Impacto</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <script>
        window.Laravel = {!! json_encode([
            'csrfToken' => csrf_token(),
        ]) !!};
    </script>
    <link href="{{url("materialize/css/materialize.css")}}" rel="stylesheet" type="text/css"/>
    <link href="{{url("material-design-icones/css/materialdesignicons.css")}}" rel="stylesheet" type="text/css">
  @yield('css')
  <link rel="stylesheet" href="/css/style.css" type="text/css">

</head>

<body>
<style media="screen">
  body {
    background-color: rgb(207, 221, 204);
  }
</style>
@if(Auth::guest())
 {{abort(403, 'Ação não autorizada.')}}
@else
   @include('templates.nav-bar-menu')
  @yield('content')
@endif




@yield('scripts')

<script>
    $(".button-collapse").sideNav({
        menuWidth: 300, // Default is 300
        edge: 'left', // Choose the horizontal origin
        closeOnClick: true, // Closes side-nav on <a> clicks, useful for Angular/Meteor
        draggable: true // Choose whether you can drag to open on touch screens
    });
</script>

</body>


</html>